name: On Push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Only
        env:
          # GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
        run: |
          echo "$GITHUB_CONTEXT"